// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StageZero.Data;

#nullable disable

namespace StageZero.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260927205007_CollapseIpHistoryIntoRuns")]
    partial class CollapseIpHistoryIntoRuns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Lifted.BlazorAuth.Basic.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailVerificationCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailVerificationCodeExpiry")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordResetCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordResetCodeExpiry")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresPasswordChange")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StageZero.Models.AccessServiceToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudflareTokenId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CreatedByStageZero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Duration")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CloudflareTokenId")
                        .IsUnique();

                    b.ToTable("AccessServiceTokens");
                });

            modelBuilder.Entity("StageZero.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("StageZero.Models.DnsProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedApiToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoneId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DnsProviders");
                });

            modelBuilder.Entity("StageZero.Models.DnsRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DnsProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DnsProviderId");

                    b.ToTable("DnsRecords");
                });

            modelBuilder.Entity("StageZero.Models.IpCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Confirmations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsChanged")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CheckedAt");

                    b.ToTable("IpChecks");
                });

            modelBuilder.Entity("StageZero.Models.TunnelConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CloudflareAccountId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudflareZoneId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudflareZoneName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedApiToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TunnelId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TunnelName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TunnelConfigs");
                });

            modelBuilder.Entity("StageZero.Models.TunnelRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ForwardHost")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("ForwardPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ForwardScheme")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DomainName")
                        .IsUnique();

                    b.HasIndex("IsEnabled");

                    b.ToTable("TunnelRoutes");
                });

            modelBuilder.Entity("StageZero.Models.DnsRecord", b =>
                {
                    b.HasOne("StageZero.Models.DnsProvider", "DnsProvider")
                        .WithMany("DnsRecords")
                        .HasForeignKey("DnsProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DnsProvider");
                });

            modelBuilder.Entity("StageZero.Models.TunnelRoute", b =>
                {
                    b.OwnsOne("StageZero.Models.RouteAccessSettings", "Access", b1 =>
                        {
                            b1.Property<int>("TunnelRouteId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("AllowedEmailDomains")
                                .HasColumnType("TEXT")
                                .HasColumnName("AccessAllowedEmailDomains");

                            b1.Property<string>("AllowedEmails")
                                .HasColumnType("TEXT")
                                .HasColumnName("AccessAllowedEmails");

                            b1.Property<string>("AllowedIdpIds")
                                .HasColumnType("TEXT")
                                .HasColumnName("AccessAllowedIdpIds");

                            b1.Property<string>("ApplicationId")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("AccessApplicationId");

                            b1.Property<bool>("CreateServiceToken")
                                .HasColumnType("INTEGER")
                                .HasColumnName("AccessCreateServiceToken");

                            b1.Property<string>("IdentityPolicyId")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("AccessIdentityPolicyId");

                            b1.Property<string>("Mode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("AccessMode");

                            b1.Property<string>("ServiceTokenDuration")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("AccessServiceTokenDuration");

                            b1.Property<string>("ServiceTokenId")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("AccessServiceTokenId");

                            b1.Property<string>("ServiceTokenName")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT")
                                .HasColumnName("AccessServiceTokenName");

                            b1.Property<string>("ServiceTokenPolicyId")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("AccessServiceTokenPolicyId");

                            b1.Property<string>("SessionDuration")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("AccessSessionDuration");

                            b1.Property<DateTime?>("SyncedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("AccessSyncedAt");

                            b1.HasKey("TunnelRouteId");

                            b1.ToTable("TunnelRoutes");

                            b1.WithOwner()
                                .HasForeignKey("TunnelRouteId");
                        });

                    b.Navigation("Access")
                        .IsRequired();
                });

            modelBuilder.Entity("StageZero.Models.DnsProvider", b =>
                {
                    b.Navigation("DnsRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
